basePath: /
definitions:
  advert_api.AdvertRequest:
    properties:
      href:
        type: string
      images:
        type: string
      is_show:
        type: boolean
      title:
        type: string
    required:
    - href
    - images
    - title
    type: object
  ctype.ImageType:
    enum:
    - 1
    - 2
    type: integer
    x-enum-comments:
      Local: 本地
      QiNiu: 七牛云
    x-enum-varnames:
    - Local
    - QiNiu
  images_api.ImageResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      path:
        type: string
    type: object
  images_api.ImageUpdateRequest:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  models.AdvertModel:
    properties:
      create_at:
        type: string
      href:
        type: string
      id:
        type: integer
      images:
        type: string
      is_show:
        type: boolean
      title:
        type: string
    type: object
  models.ImageModel:
    properties:
      create_at:
        type: string
      hash:
        description: 图片哈希值，用于判断重复图片
        type: string
      id:
        type: integer
      image_type:
        allOf:
        - $ref: '#/definitions/ctype.ImageType'
        description: 图片存储类型
      name:
        description: 图片名称
        type: string
      path:
        description: 图片路径
        type: string
    type: object
  models.RemoveRequest:
    properties:
      id_list:
        items:
          type: integer
        type: array
    type: object
  res.ListResponse-models_AdvertModel:
    properties:
      count:
        type: integer
      list:
        $ref: '#/definitions/models.AdvertModel'
    type: object
  res.ListResponse-models_ImageModel:
    properties:
      count:
        type: integer
      list:
        $ref: '#/definitions/models.ImageModel'
    type: object
  res.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
host: 127.0.0.01:8080
info:
  contact: {}
  description: GoRoLingG API文档
  title: GoRoLingG API文档
  version: "1.0"
paths:
  /api/advertList:
    get:
      description: 广告列表，用于展示广告
      parameters:
      - description: 模糊匹配的关键字
        in: query
        name: key
        type: string
      - description: 每页限制显示量
        in: query
        name: limit
        type: integer
      - description: 页数
        in: query
        name: page
        type: integer
      - description: 排序
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.ListResponse-models_AdvertModel'
              type: object
      summary: 广告列表
      tags:
      - 广告管理
  /api/advertRemove:
    delete:
      description: 广告删除，用于批量删除广告
      parameters:
      - description: 要删除的广告id列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 广告删除
      tags:
      - 广告管理
  /api/advertUpdate/:id:
    put:
      description: 广告更新
      parameters:
      - description: 广告更新的一些参数
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/advert_api.AdvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 广告更新
      tags:
      - 广告管理
  /api/advertUpload:
    post:
      description: 创建广告
      parameters:
      - description: 添加新广告的一些参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advert_api.AdvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 创建广告
      tags:
      - 广告管理
  /api/imagesList:
    get:
      description: 图片列表，用于显示所有的图片
      parameters:
      - description: 模糊匹配的关键字
        in: query
        name: key
        type: string
      - description: 每页限制显示量
        in: query
        name: limit
        type: integer
      - description: 页数
        in: query
        name: page
        type: integer
      - description: 排序
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.ListResponse-models_ImageModel'
              type: object
      summary: 图片列表
      tags:
      - 图片管理
  /api/imagesNameList:
    get:
      description: 图片列表，用于精简显示所有的图片数据
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/images_api.ImageResponse'
                  type: array
              type: object
      summary: 图片列表精简查询
      tags:
      - 图片管理
  /api/imagesRemove:
    delete:
      description: 图片删除，用于批量删除数据库内的图片数据
      parameters:
      - description: 要删除的图片id列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 图片删除
      tags:
      - 图片管理
  /api/imagesUpdate:
    put:
      description: 图片更新，用于更新图片名字
      parameters:
      - description: 要更新的图片id和更改后的name
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/images_api.ImageUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: 图片更新
      tags:
      - 图片管理
  /api/imagesUpload:
    post:
      consumes:
      - multipart/form-data
      description: 添加图片，提供图片上传功能
      parameters:
      - description: 上传的图片文件
        in: formData
        name: images
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 操作成功
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 添加图片
      tags:
      - 图片管理
swagger: "2.0"
